### PR TITLE
Fix ELASTIC_PASSWORD for open X-Pack

### PR DESCRIPTION
**Pull request by jarpy**

### CODE REVIEW

**Comment by jamiesmith** [comment]
I think this needs a minor change which I can't confirm yet.  
IF the ELASTIC_PASSWORD is set, you should delete the bootstrap.password keystore:

`(run_as_other_user_if_needed  elasticsearch-keystore remove bootstrap.password)`

Blindly setting it will fail if the image already has one burned in (as we do with demos)

**Comment by jarpy** [comment]
To cut down on the amount of mutation, I suggest we:

```bash
if ! (run_as_other_user_if_needed elasticsearch-keystore list | grep -q '^bootstrap.password$'); then
    (run_as_other_user_if_needed echo "$ELASTIC_PASSWORD" | elasticsearch-keystore add -x 'bootstrap.password')
fi
```

**Comment by jamiesmith** [comment]
That says "if it is already there don't do it"

What takes precedence? Letting an environment variable override the config (I think), or keeping a baked in password and ignoring the env var?  

I contend that if a user supplies the ELASTIC_PASSWORD they want it to _replace_ the one in the bootstrap, which means you need to delete it so you can write it

**Comment by jarpy** [comment]
I agree about the user expectation, but the variable is setting the bootstrap password, rather than the actual user password for `elastic` et. al. The bootstrap process should only occur once in the lifetime of a cluster.

**Pull request merged**
