### PR TITLE
Flavour in image name

### PR DESCRIPTION
**Pull request by jarpy**
Move image flavor to repository, not tag.

The release manager is built with the expectation that the version tag
of any Docker image will contain strictly the ELASTIC_VERSION. When we
overload the version tag with the image flavour, we break that
expectation.

This patch moves the image flavour from the tag to the repository, so
instead of getting image names like:

  `elasticsearch:6.0.0-beta2-platinum`

You get ones like:

  `elasticsearch-platinum:6.0.0-beta2`

### CODE REVIEW

**Comment by jarpy** [comment]
cc @dliappis

**Comment by xeraa** [comment]
Is this a good solution longterm? Looking at other popular images, like https://hub.docker.com/_/nginx/, it seems to be common to keep the flavour in the tag and always have the same image name.

**Comment by jarpy** [comment]
We have an incredibly strong concept of the "version" at Elastic, right down to staging build versions like `6.0.0-beta2-d2816397`. I think swimming against that tide, and being the only products that overload and extend that string may a bit too wild and crazy.

**Comment by xeraa** [comment]
I guess it comes down to swimming against the Docker crowd or the Elastic build tide — honestly not sure which is better or worse

**Comment by jarpy** [comment]
Compared to hosting the images on our own, special registry, it's a drop in
the ocean. :D

**Pull request merged**
