### PR TITLE
Do not use host network for building image

### PR DESCRIPTION
**Pull request by jasontedor**
Today the Elasticsearch Docker build relies on the host network for building the Docker image. In particular, it requires port 8000 on the host to be available so that the Docker build can connect to the artifacts server that is created during an earlier phase of the build. I ran into a strange issue where the build would repeatedly fail if using the host network. In particular, the issue that I ran into is that the setup package installed during yum update could not be installed because /etc/hosts could not be extracted from the package. It is not clear to me why this fails with the host network, but once we surmised this was a possbility and switched to not use the host network, the issue went anyway. Whatever the issue is, it's inherently desirable to not use the host network during the build anyway. Instead, we can connect the containers over a dedicated bridge network and not rely on port 8000 being available on the host. Fortunately, this fixes the issue that I was running into as well.

### CODE REVIEW

**Comment by jasontedor** [comment]
The fastest reproduction for me is:

```
[jason@totoro elasticsearch-docker]$ docker run --rm --network=host -it centos:7 /bin/bash                                                                                                                                                                                  
[root@totoro /]# yum install -y setup
Loaded plugins: fastestmirror, ovl
base                                                                                                                                                                                                                                                  | 3.6 kB  00:00:00    
extras                                                                                                                                                                                                                                                | 3.4 kB  00:00:00    
updates                                                                                                                                                                                                                                               | 3.4 kB  00:00:00    
(1/4): base/7/x86_64/group_gz                                                                                                                                                                                                                         | 166 kB  00:00:00    
(2/4): extras/7/x86_64/primary_db                                                                                                                                                                                                                     | 125 kB  00:00:00    
(3/4): updates/7/x86_64/primary_db                                                                                                                                                                                                                    | 1.0 MB  00:00:00    
(4/4): base/7/x86_64/primary_db                                                                                                                                                                                                                       | 5.9 MB  00:00:01    
Determining fastest mirrors
 * base: centos.mirror.constant.com
 * extras: centos.mirror.constant.com
 * updates: centos.mirror.constant.com
Resolving Dependencies
--> Running transaction check
---> Package setup.noarch 0:2.8.71-7.el7 will be updated
---> Package setup.noarch 0:2.8.71-9.el7 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

=============================================================================================================================================================================================================================================================================
 Package                                                        Arch                                                            Version                                                                  Repository                                                     Size
=============================================================================================================================================================================================================================================================================
Updating:
 setup                                                          noarch                                                          2.8.71-9.el7                                                             base                                                          166 k

Transaction Summary
=============================================================================================================================================================================================================================================================================
Upgrade  1 Package

Total download size: 166 k
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
warning: /var/cache/yum/x86_64/7/base/packages/setup-2.8.71-9.el7.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY===========================================================                                            ]  0.0 B/s | 100 kB  --:--:-- ETA
Public key for setup-2.8.71-9.el7.noarch.rpm is not installed
setup-2.8.71-9.el7.noarch.rpm                                                                                                                                                                                                                         | 166 kB  00:00:00    
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Importing GPG key 0xF4A80EB5:
 Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
 Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
 Package    : centos-release-7-4.1708.el7.centos.x86_64 (@CentOS)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Updating   : setup-2.8.71-9.el7.noarch                                                                                                                                                                                                                                 1/2
Error unpacking rpm package setup-2.8.71-9.el7.noarch
warning: /etc/group created as /etc/group.rpmnew
error: unpacking of archive failed on file /etc/hosts: cpio: rename
setup-2.8.71-7.el7.noarch was supposed to be removed but is not!
  Verifying  : setup-2.8.71-7.el7.noarch                                                                                                                                                                                                                                 1/2
  Verifying  : setup-2.8.71-9.el7.noarch                                                                                                                                                                                                                                 2/2

Failed:
  setup.noarch 0:2.8.71-7.el7                                                                                                           setup.noarch 0:2.8.71-9.el7                                                                                                         

Complete!
[root@totoro /]# 
```

With:

```
[jason@totoro elasticsearch-docker]$ docker run --rm --cap-add SYS_PTRACE --network=host -it centos:7 /bin/bash                                                                                                                                                     [21/1943]
[root@totoro /]# yum install -y strace                                                                                                                                                                                                                                      
Loaded plugins: fastestmirror, ovl                                                                                                                                                                                                                                          
base                                                                                                                                                                                                                                                  | 3.6 kB  00:00:00    
extras                                                                                                                                                                                                                                                | 3.4 kB  00:00:00    
updates                                                                                                                                                                                                                                               | 3.4 kB  00:00:00    
(1/4): extras/7/x86_64/primary_db                                                                                                                                                                                                                     | 125 kB  00:00:00    
(2/4): base/7/x86_64/group_gz                                                                                                                                                                                                                         | 166 kB  00:00:01    
(3/4): base/7/x86_64/primary_db                                                                                                                                                                                                                       | 5.9 MB  00:00:01    
(4/4): updates/7/x86_64/primary_db                                                                                                                                                                                                                    | 1.0 MB  00:00:03    
Determining fastest mirrors
 * base: centos.mirror.constant.com
 * extras: centos.mirror.constant.com
 * updates: centos.mirror.constant.com
Resolving Dependencies                                                                                                                                                                                                                                                      
--> Running transaction check                                                                                                                                                                                                                                               
---> Package strace.x86_64 0:4.12-6.el7 will be installed                                                                                                                                                                                                                   
--> Finished Dependency Resolution                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                            
Dependencies Resolved                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                            
=============================================================================================================================================================================================================================================================================
 Package                                                          Arch                                                             Version                                                              Repository                                                      Size
=============================================================================================================================================================================================================================================================================
Installing:                                                                                                                                                                                                                                                                 
 strace                                                           x86_64                                                           4.12-6.el7                                                           base                                                           459 k
                                                                                                                                                                                                                                                                            
Transaction Summary                                                                                                                                                                                                                                                         
=============================================================================================================================================================================================================================================================================
Install  1 Package                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                            
Total download size: 459 k
Installed size: 1.7 M                                                                                                                                                                                                                                                       
Downloading packages:                                                                                                                                                                                                                                                       
warning: /var/cache/yum/x86_64/7/base/packages/strace-4.12-6.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY=================-                                                                                      ]  0.0 B/s |  99 kB  --:--:-- ETA
Public key for strace-4.12-6.el7.x86_64.rpm is not installed                                                                                                                                                                                                                
strace-4.12-6.el7.x86_64.rpm                                                                                                                                                                                                                          | 459 kB  00:00:00    
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Importing GPG key 0xF4A80EB5:
 Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
 Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5                                                                                                                                                                                                             
 Package    : centos-release-7-4.1708.el7.centos.x86_64 (@CentOS)                                                                                                                                                                                                           
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7                                                                                                                                                                                                                         
Running transaction check
Running transaction test
Transaction test succeeded                                                                                                                                                                                                                                                  
Running transaction                                                                                                                                                                                                                                                         
  Installing : strace-4.12-6.el7.x86_64                                                                                                                                                                                                                                  1/1
  Verifying  : strace-4.12-6.el7.x86_64                                                                                                                                                                                                                                  1/1

Installed:
  strace.x86_64 0:4.12-6.el7

Complete!
[root@totoro /]# strace yum install -y setup 2>&1 | grep "rename.*/etc/hosts" -C10
write(40, "127.0.0.1   localhost localhost."..., 158) = 158
close(40)                               = 0
ioctl(1, TCGETS, 0x7ffc5a124830)        = -1 ENOTTY (Inappropriate ioctl for device)
getuid()                                = 0
getuid()                                = 0
chown("/etc/hosts;5afb0948", 0, 0)      = 0
chmod("/etc/hosts;5afb0948", 0644)      = 0
utime("/etc/hosts;5afb0948", [2013/06/07-14:31:32, 2013/06/07-14:31:32]) = 0
getuid()                                = 0
lstat("/etc/hosts", {st_mode=S_IFREG|0644, st_size=158, ...}) = 0
rename("/etc/hosts;5afb0948", "/etc/hosts") = -1 EBUSY (Device or resource busy)                                                                                                                                                                                            
munmap(0x7feff1c20000, 2101248)         = 0                                                                                                                                                                                                                                 
close(39)                               = 0
munmap(0x7ff000811000, 4096)            = 0
ioctl(1, TCGETS, 0x7ffc5a1249d0)        = -1 ENOTTY (Inappropriate ioctl for device)
ioctl(1, TCGETS, 0x7ffc5a1249d0)        = -1 ENOTTY (Inappropriate ioctl for device)                                                                                                                                                                                        
ioctl(1, TIOCGWINSZ, 0x7ffc5a123a40)    = -1 ENOTTY (Inappropriate ioctl for device)                                                                                                                                                                                        
write(1, "  Updating   : setup-2.8.71-9.el"..., 79  Updating   : setup-2.8.71-9.el7.noarch                                    1/2) = 79                                                                                                                                     
write(23, "error: unpacking of archive fail"..., 68) = 68
write(2, "Error unpacking rpm package setu"..., 53Error unpacking rpm package setup-2.8.71-9.el7.noarch) = 53
write(2, "\n", 1
```

it appears this has something to do with the fact that `/etc/hosts` is bind mounted in as a single file, the key line being:

```
rename("/etc/hosts;5afb0948", "/etc/hosts") = -1 EBUSY (Device or resource busy) 
```

**Comment by jarpy** [comment]
This is excellent. I'll be sure to steal this for the next-gen build system.

**Comment by jarpy** [comment]
How does name resolution work from the Docker host to the container?

```
Step 8/28 : RUN curl -fsSL http://elasticsearch-docker-artifact-server:8000/elasticsearch/distribution/archives/oss-tar/build/distributions/elasticsearch-oss-7.0.0-alpha1.tar.gz |     tar zx --strip-components=1
 ---> Running in 0f27516b0720
curl: (6) Could not resolve host: elasticsearch-docker-artifact-server; Name or service not known
```

**Comment by jarpy** [comment]
Sorry. I was calling the wrong Make target. Docker network name resolution usually "just works". I should have realised the fault was mine.

**Pull request merged**
