### PR TITLE
Fix link to documentation

### LINKED ISSUE #29: 404 in README
The link referenced in the README ("Elastic web site") points to a page which does not exist.

### PR DESCRIPTION
**Pull request by antoineco**
Closes #29

### CODE REVIEW

**Comment by antoineco** [comment]
CLA signed

**Comment by jarpy** [comment]
Thanks. Both `master` and `current` work, but `current` is a better choice, I agree.

At some point, we'll probably want each branch to point to its exact version number, like:

https://www.elastic.co/guide/en/elasticsearch/reference/5.1/docker.html

Cheers.

**Comment by antoineco** [comment]
Oh, that's true. The main intention was to fix the 404 I had today visiting `master`, but it works now. Anyway, thanks for merging :)

**Comment by jarpy** [comment]
No problem. Sorry about the 404! :s

**Pull request merged**
