### PR TITLE
Change elasticsearch home dir to /elasticsearch

### PR DESCRIPTION
**Pull request by dliappis**
In an effort to make the Docker experience easier and more consistent across the Elastic stack images, we take a small detour from the Linux FHS and install under /elasticsearch.

Adjust documentation to refer to /elasticsearch. A symlink is kept towards /usr/share/elasticsearch for backwards compatibility.

Workaround the home dir set for the elasticsearch user in the base image until a new base image is pushed.

### CODE REVIEW

**Comment by dliappis** [comment]
@jarpy FYI, prototype version

**Comment by inqueue** [comment]
Interesting deviation. All packaged products in the Elastic Stack are using `/usr/share/<product_name>` as of 5.0. Might this change add confusion?

**Comment by dliappis** [comment]
@inqueue This is certainly up for discussion: came up as a topic over a chat with @jarpy. [LFHS](http://tldp.org/LDP/Linux-Filesystem-Hierarchy/Linux-Filesystem-Hierarchy.pdf) doesn't really seem to promote the use of `/usr/share` for this purpose though. The motivation was that as dirs need to be bind mounted e.g. for ES or logstash confs, shorter paths come handy, but good that you brought it up. 

@jarpy what do you think, esp. in light of standardization in deb/rpm packages for /usr/share/<product_name>?

**Comment by inqueue** [comment]
Thanks @dliappis. I always thought it should have been `/opt` as opposed to `/usr/share`, but I figured someone had a reason so I let it go. I'm all for shorter paths and whatever makes things easier and consistent. Someone with more experience with Docker should weigh in :)

**Comment by dliappis** [comment]
@inqueue Synced up with @jarpy with 5.0 standardizing on `/usr/share/<product>`. Yes we all agree it would cause confusion to change it, esp. with people getting used to `/usr/share/<product>` on non docker installations. I will close this PR.

**Pull request closed without merging**
